# Generated by Django 3.1 on 2020-08-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cassandra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FristName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Age', models.PositiveIntegerField(blank=True, null=True)),
                ('Descripton', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
