# Generated by Django 3.1 on 2020-08-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cassandra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cassandra',
            old_name='Descripton',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='cassandra',
            old_name='FristName',
            new_name='FirstName',
        ),
    ]
